Nosto/nosto-js

- src/index.ts
- src/lib/init.ts
- src/lib/nostojs.ts
- src/types.ts
- src/utils/dom.ts
> Minor docs improvements

- .github/workflows/createRelease.yml
> Switch runs on to non-self hosted setup

- .github/workflows/scripts/release.sh
> Adjust commit message

- src/client/nosto.d.ts
> Search options fixes

- src/lib/init.ts
> typedoc - Add docs for initprops fields

- package.json
> Fix testing path

- src/testing/mockNostojs.ts
- test/mockNostojs.spec.ts
- tsconfig.json
> Make mock api type more flexible

- src/client/nosto.d.ts
- test/build.spec.ts
> Remove axios type leak

- src/testing/mockNostojs.ts
> Expose MockAPI

- src/testing/mockNostojs.ts
- test/mockNostojs.spec.ts
> Add nosto window mock

- .github/workflows/ci.yml
- .github/workflows/createRelease.yml
- .github/workflows/publish.yml
> Bump node version

- src/index.ts
- test/node.spec.ts
To make sure that module initialization also works when window is not defined
https://github.com/Nosto/nosto-js/issues/92
> Add invocation guard

- src/lib/init.ts
- test/init.spec.ts
https://nostosolutions.atlassian.net/browse/CFE-681
> Add support for shopify international

- src/lib/init.ts
- test/init.spec.ts
> Improve scriptloader logic

- src/client/nosto.d.ts
> Bump nosto.d.ts

- eslint.config.js
- package-lock.json
- package.json
- src/index.ts
- src/testing/testing.ts
https://nostosolutions.atlassian.net/browse/CFE-753
> Limit barrel file usage

- eslint.config.js
- package.json
Scope the barrel file eslint rules to src contents
> Scope barrel file eslint rules

- src/index.ts
- src/lib/nostojs.ts
- src/lib/settings.ts
- src/testing/mockSettings.ts
- src/testing/testing.ts
- test/settings.spec.ts
> feat: add settings utility

- package.json
- src/client/nosto.d.ts
> fix: bump nosto dts

- src/client/nosto.d.ts
> fix: bump nosto dts again

- src/index.ts
- src/testing/testing.ts
> Add missing exports back

- src/testing/mockNostojs.ts
- test/mockNostojs.spec.ts
Merges defaults to mock api to make mock api usage easier
> Merge defaults into mock api

- .github/workflows/publish.yml
> Bump action versions

- src/client/nosto.d.ts
> Sync nosto.d.ts

- .gitignore
BREAKING CHANGE: force release
> chore!: force release

- .github/workflows/ci.yml
- .gitignore
- package-lock.json
- package.json
- test/addSkuToCart.spec.ts
- test/helpers.spec.ts
- test/measure.spec.ts
- test/mockNostojs.spec.ts
- test/reloadNosto.spec.ts
- vite.config.ts
https://nostosolutions.atlassian.net/browse/CFE-1024
> chore: add test coverage threshold

- src/client/nosto.d.ts
> feat: bump nosto.d.ts

- src/client/nosto.d.ts
> fix: bump nosto.d.ts

- package.json
> chore: add typedoc script with json result

- .github/copilot-instructions.md
- .github/instructions/coding.instructions.md
- .github/instructions/github-actions.instructions.md
- .github/instructions/testing.instructions.md
> chore: split copilot config
